name = "speedreader"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[routes]]
pattern = "speedreader.nathanchung.dev"
custom_domain = true
